version: '3'
services:
  db_postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: notes_microservices

  auth_service:
    depends_on:
      - db_postgres
    build:
      context: auth-service
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    volumes:
      - ./auth-service:/app/