version: '3'
services:

  auth_service:
    depends_on:
      - db_postgres
    build:
      context: auth-service
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/app/

  db_postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: notes_microservices